#!/bin/bash

# Folder Reorganization Script
# Date: 2025-11-02

echo "📁 Starting Folder Reorganization..."
echo ""

# Create new structure
echo "Creating new folder structure..."
mkdir -p .archive/old-frontend
mkdir -p .archive/old-services
mkdir -p .build/artifacts
mkdir -p .build/cache
mkdir -p config/validators
mkdir -p data/deployments

echo "✅ New structure created"
echo ""

# Move frontend (archived - in another codebase)
echo "Archiving frontend..."
if [ -d "frontend" ]; then
  mv frontend .archive/old-frontend/ 2>/dev/null
  echo "✅ frontend/ → .archive/old-frontend/"
fi

# Move services (archived - moved to xaheen-sdk/api)
echo "Archiving services..."
if [ -d "services" ]; then
  mv services .archive/old-services/ 2>/dev/null
  echo "✅ services/ → .archive/old-services/"
fi

# Move public (seems related to frontend)
echo "Archiving public..."
if [ -d "public" ]; then
  mv public .archive/old-frontend/ 2>/dev/null
  echo "✅ public/ → .archive/old-frontend/"
fi

echo ""

# Move validator data folders
echo "Reorganizing validator data..."
if [ -d "validator" ]; then
  mv validator config/validators/validator-base 2>/dev/null
  echo "✅ validator/ → config/validators/validator-base/"
fi

if [ -d "validator-1" ]; then
  mv validator-1 config/validators/ 2>/dev/null
  echo "✅ validator-1/ → config/validators/"
fi

if [ -d "validator-2" ]; then
  mv validator-2 config/validators/ 2>/dev/null
  echo "✅ validator-2/ → config/validators/"
fi

if [ -d "validator-3" ]; then
  mv validator-3 config/validators/ 2>/dev/null
  echo "✅ validator-3/ → config/validators/"
fi

echo ""

# Move build artifacts
echo "Reorganizing build artifacts..."
if [ -d "artifacts" ]; then
  mv artifacts .build/ 2>/dev/null
  echo "✅ artifacts/ → .build/artifacts/"
fi

if [ -d "cache" ]; then
  mv cache .build/ 2>/dev/null
  echo "✅ cache/ → .build/cache/"
fi

# Move deployments
if [ -d "deployments" ] && [ "$(ls -A deployments 2>/dev/null)" ]; then
  mv deployments/* data/deployments/ 2>/dev/null
  rmdir deployments 2>/dev/null
  echo "✅ deployments/ → data/deployments/"
else
  rm -rf deployments 2>/dev/null
  echo "✅ Empty deployments/ removed"
fi

echo ""

# Create .gitignore for build artifacts
cat > .build/.gitignore << 'GITIGNORE'
# Ignore all build artifacts
*
!.gitignore
!README.md
GITIGNORE

# Create .build README
cat > .build/README.md << 'BUILDREADME'
# Build Artifacts

This directory contains Hardhat build outputs.

## Structure

- **artifacts/** - Compiled contract artifacts (ABIs, bytecode)
- **cache/** - Hardhat compilation cache

## Regeneration

These files are automatically generated by Hardhat:

```bash
# Clean build artifacts
rm -rf .build/artifacts .build/cache

# Recompile
npx hardhat compile
```

**Note**: This directory is gitignored. Build artifacts are regenerated on each compile.
BUILDREADME

echo "✅ Build README created"
echo ""

# Create validators README
cat > config/validators/README.md << 'VALIDATORSREADME'
# Validator Data Directories

This directory contains validator node data and keystores.

## Structure

- **validator-base/** - Base validator configuration
- **validator-1/** - Validator 1 blockchain data
- **validator-2/** - Validator 2 blockchain data
- **validator-3/** - Validator 3 blockchain data

## Contents

Each validator directory contains:
- `geth/` - Blockchain data (leveldb)
- `keystore/` - Validator private keys (⚠️ SECURE!)
- `password.txt` - Keystore password (⚠️ SECURE!)

## Security

⚠️ **CRITICAL**: These directories contain sensitive cryptographic keys!

- Never commit to git (gitignored)
- Backup securely
- Encrypt at rest
- Restrict file permissions

## Usage

Validators reference these directories:
```bash
# Docker volume mounts
-v $(pwd)/config/validators/validator-1:/bsc

# Direct path
--datadir config/validators/validator-1
```
VALIDATORSREADME

echo "✅ Validators README created"
echo ""

# Create archive README
cat > .archive/README.md << 'ARCHIVEREADME'
# Archived Components

This directory contains components that have been moved, deprecated, or replaced.

## Contents

- **old-frontend/** - Original frontend (moved to separate repository)
- **old-services/** - Original services (moved to xaheen-sdk/api)
- **cleanup-scripts/** - Cleanup automation scripts

## Why Archived?

**Frontend**: Development moved to separate repository for better organization
**Services**: Consolidated into xaheen-sdk/api for unified backend
**Scripts**: Historical cleanup automation (kept for reference)

## Recovery

If you need to restore any archived component:

```bash
# Example: Restore old services for reference
cp -r .archive/old-services services-reference
```

**Note**: Archived components may be outdated. Use as reference only.
ARCHIVEREADME

echo "✅ Archive README created"
echo ""

# Summary
echo "📊 Folder Reorganization Summary:"
echo ""
echo "Archived:"
echo "  - frontend/ → .archive/old-frontend/"
echo "  - services/ → .archive/old-services/"
echo "  - public/ → .archive/old-frontend/"
echo ""
echo "Moved:"
echo "  - validator* → config/validators/"
echo "  - artifacts/ → .build/artifacts/"
echo "  - cache/ → .build/cache/"
echo "  - deployments/ → data/deployments/"
echo ""
echo "Created:"
echo "  - .build/README.md"
echo "  - config/validators/README.md"
echo "  - .archive/README.md"
echo ""
echo "✅ Folder reorganization complete!"
echo ""
echo "⚠️  NEXT STEP: Update hardhat.config.js to use new paths"
