#!/bin/bash
# Fix SSH Access to BSC Validator Server
# Automatically detects instance, updates security group, and uploads genesis file

set -e

echo "========================================="
echo "Fix SSH Access & Deploy Genesis"
echo "========================================="

# Configuration
SERVER_IP="3.91.50.187"
GENESIS_FILE="data/genesis-btcbr-fixed.json"

# Step 1: Get current public IP
echo -e "\n1. Getting your current public IP..."
CURRENT_IP=$(curl -4 -s ifconfig.me)
echo "   Your IP: $CURRENT_IP"

# Step 2: Find instance ID
echo -e "\n2. Finding EC2 instance..."
INSTANCE_ID=$(aws ec2 describe-instances \
  --filters "Name=ip-address,Values=$SERVER_IP" \
  --query 'Reservations[*].Instances[*].InstanceId' \
  --output text)

if [ -z "$INSTANCE_ID" ]; then
    echo "   ❌ Error: Instance not found at IP $SERVER_IP"
    exit 1
fi
echo "   Instance ID: $INSTANCE_ID"

# Step 3: Get instance details
echo -e "\n3. Getting instance configuration..."
INSTANCE_INFO=$(aws ec2 describe-instances \
  --instance-ids "$INSTANCE_ID" \
  --query 'Reservations[*].Instances[*].[SecurityGroups[0].GroupId,KeyName,ImageId]' \
  --output text)

SECURITY_GROUP=$(echo "$INSTANCE_INFO" | awk '{print $1}')
KEY_NAME=$(echo "$INSTANCE_INFO" | awk '{print $2}')
IMAGE_ID=$(echo "$INSTANCE_INFO" | awk '{print $3}')

echo "   Security Group: $SECURITY_GROUP"
echo "   SSH Key: $KEY_NAME"
echo "   AMI: $IMAGE_ID"

# Step 4: Determine SSH username from AMI
echo -e "\n4. Determining SSH username..."
AMI_NAME=$(aws ec2 describe-images \
  --image-ids "$IMAGE_ID" \
  --query 'Images[*].Name' \
  --output text)

if [[ "$AMI_NAME" == *"ubuntu"* ]]; then
    SSH_USER="ubuntu"
elif [[ "$AMI_NAME" == *"amzn"* ]] || [[ "$AMI_NAME" == *"amazon"* ]]; then
    SSH_USER="ec2-user"
elif [[ "$AMI_NAME" == *"debian"* ]]; then
    SSH_USER="admin"
else
    SSH_USER="ec2-user"
fi

echo "   SSH Username: $SSH_USER"
echo "   AMI Name: $AMI_NAME"

# Step 5: Find SSH key locally
echo -e "\n5. Locating SSH key..."
KEY_PATH=""
for key in ~/.ssh/$KEY_NAME.pem ~/.ssh/btcbr-key.pem ~/.ssh/bsc-validator-key.pem; do
    if [ -f "$key" ]; then
        KEY_PATH="$key"
        chmod 400 "$KEY_PATH"
        echo "   Found key: $KEY_PATH"
        break
    fi
done

if [ -z "$KEY_PATH" ]; then
    echo "   ❌ Error: SSH key not found!"
    echo "   Searched for: $KEY_NAME.pem, btcbr-key.pem, bsc-validator-key.pem"
    echo ""
    echo "   Please place the SSH key in ~/.ssh/ and try again"
    exit 1
fi

# Step 6: Update security group
echo -e "\n6. Updating security group for SSH access..."
if aws ec2 authorize-security-group-ingress \
    --group-id "$SECURITY_GROUP" \
    --protocol tcp \
    --port 22 \
    --cidr "$CURRENT_IP/32" 2>/dev/null; then
    echo "   ✅ SSH access granted from $CURRENT_IP"
else
    echo "   ℹ️  SSH rule already exists or couldn't be added"
fi

# Step 7: Test SSH connection
echo -e "\n7. Testing SSH connection..."
if ssh -i "$KEY_PATH" -o ConnectTimeout=10 -o StrictHostKeyChecking=no \
    "$SSH_USER@$SERVER_IP" "echo 'Connection successful'" 2>/dev/null; then
    echo "   ✅ SSH connection works!"
else
    echo "   ❌ SSH connection failed!"
    echo ""
    echo "   Troubleshooting:"
    echo "   - Verify key: $KEY_PATH"
    echo "   - Username: $SSH_USER"
    echo "   - Server: $SERVER_IP"
    echo ""
    exit 1
fi

# Step 8: Upload genesis file
echo -e "\n8. Uploading fixed genesis file..."
if [ ! -f "$GENESIS_FILE" ]; then
    echo "   ❌ Error: Genesis file not found at $GENESIS_FILE"
    exit 1
fi

scp -i "$KEY_PATH" "$GENESIS_FILE" "$SSH_USER@$SERVER_IP:~/bsc-production/config/genesis.json"
echo "   ✅ Genesis file uploaded"

# Step 9: Save configuration
echo -e "\n9. Saving configuration..."
cat > .ssh-config << EOF
# BSC Server SSH Configuration
# Auto-generated by fix-ssh-access.sh
SERVER_IP=$SERVER_IP
INSTANCE_ID=$INSTANCE_ID
SECURITY_GROUP=$SECURITY_GROUP
SSH_USER=$SSH_USER
KEY_NAME=$KEY_NAME
KEY_PATH=$KEY_PATH
CURRENT_IP=$CURRENT_IP
EOF

echo "   ✅ Configuration saved to .ssh-config"

echo -e "\n========================================="
echo "✅ SSH Access Fixed & Genesis Uploaded!"
echo "========================================="
echo ""
echo "Configuration:"
echo "  Server: $SSH_USER@$SERVER_IP"
echo "  Key: $KEY_PATH"
echo "  Instance: $INSTANCE_ID"
echo ""
echo "Next steps:"
echo "  1. SSH to server: ssh -i $KEY_PATH $SSH_USER@$SERVER_IP"
echo "  2. Follow manual deployment guide to reinitialize validators"
echo ""
